//Clase:InterfazGraficaRadio
//Tiene la funcion de manejar las exepciones del programa
//Hecho por: Ma. Isabel Fernandez Carnet: 13024 
//			Erick Hernandez 	  Carnet: 13197
//			Andres Lainfiesta	  Carnet: 13072
//Fecha: 17-10-2013
//***************************************************************
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
public class InterfazGraficaRadio extends javax.swing.JFrame {
    /** Creates new form InterfazGraficaRadio */
	private RadioZoe miRadio;
    public InterfazGraficaRadio() {
        initComponents();
		miRadio=new RadioZoe();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnAnterior = new javax.swing.JButton();
        lblEstacion = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        btnFav1 = new javax.swing.JButton();
        btnFav2 = new javax.swing.JButton();
        btnFav3 = new javax.swing.JButton();
        btnFav4 = new javax.swing.JButton();
        btnFav5 = new javax.swing.JButton();
        btnFav6 = new javax.swing.JButton();
        btnFav7 = new javax.swing.JButton();
        btnFav8 = new javax.swing.JButton();
        btnFav9 = new javax.swing.JButton();
        btnFav10 = new javax.swing.JButton();
        btnFav11 = new javax.swing.JButton();
        btnFav12 = new javax.swing.JButton();
        btnFrecuencia = new javax.swing.JButton();
        btnEstado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lblTitulo.setText("Radio Zoé");

        btnAnterior.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAnterior.setText("<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        lblEstacion.setText("");

        btnSiguiente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSiguiente.setText(">");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnFav1.setText("1");
        btnFav1.setActionCommand("fav1");
        btnFav1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFav1ActionPerformed(evt);
            }
        });

        btnFav2.setText("2");
        btnFav2.setActionCommand("fav2");
        btnFav2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFav2ActionPerformed(evt);
            }
        });

        btnFav3.setText("3");
        btnFav3.setActionCommand("fav3");
        btnFav3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFav3ActionPerformed(evt);
            }
        });

        btnFav4.setText("4");
        btnFav4.setActionCommand("fav4");
        btnFav4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFav4ActionPerformed(evt);
            }
        });

        btnFav5.setText("5");
        btnFav5.setActionCommand("fav5");
        btnFav5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFav5ActionPerformed(evt);
            }
        });

        btnFav6.setText("6");
        btnFav6.setActionCommand("fav6");
        btnFav6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFav6ActionPerformed(evt);
            }
        });

        btnFav7.setText("7");
        btnFav7.setActionCommand("fav7");
        btnFav7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFav7ActionPerformed(evt);
            }
        });

        btnFav8.setText("8");
        btnFav8.setActionCommand("fav8");
        btnFav8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFav8ActionPerformed(evt);
            }
        });

        btnFav9.setText("9");
        btnFav9.setActionCommand("fav9");
        btnFav9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFav9ActionPerformed(evt);
            }
        });

        btnFav10.setText("10");
        btnFav10.setActionCommand("fav10");
        btnFav10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFav10ActionPerformed(evt);
            }
        });

        btnFav11.setText("11");
        btnFav11.setActionCommand("fav11");
        btnFav11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFav11ActionPerformed(evt);
            }
        });

        btnFav12.setText("12");
        btnFav12.setActionCommand("fav12");
        btnFav12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFav12ActionPerformed(evt);
            }
        });

        btnFrecuencia.setText("AM/FM");
        btnFrecuencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrecuenciaActionPerformed(evt);
            }
        });

        btnEstado.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnEstado.setText("ON/OFF");
        btnEstado.setActionCommand("encendido");
        btnEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFav1)
                        .addGap(18, 18, 18)
                        .addComponent(btnFav2)
                        .addGap(18, 18, 18)
                        .addComponent(btnFav3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(btnFrecuencia)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFav10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFav11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFav12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFav7)
                                .addGap(18, 18, 18)
                                .addComponent(btnFav8)
                                .addGap(18, 18, 18)
                                .addComponent(btnFav9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFav4)
                                .addGap(18, 18, 18)
                                .addComponent(btnFav5)
                                .addGap(18, 18, 18)
                                .addComponent(btnFav6)))
                        .addContainerGap(189, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(btnAnterior)
                .addGap(76, 76, 76)
                .addComponent(lblEstacion)
                .addGap(53, 53, 53)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(333, Short.MAX_VALUE)
                .addComponent(btnEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstacion)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFav1)
                    .addComponent(btnFav2)
                    .addComponent(btnFav3)
                    .addComponent(btnFrecuencia))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFav4)
                    .addComponent(btnFav5)
                    .addComponent(btnFav6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFav7)
                    .addComponent(btnFav8)
                    .addComponent(btnFav9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFav10)
                    .addComponent(btnFav11)
                    .addComponent(btnFav12))
                .addGap(31, 31, 31)
                .addComponent(btnEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
		miRadio.cambiarEstacion(false);
		lblEstacion.setText(Double.toString(miRadio.getEstacion()));
		btnFav12.setBackground(Color.red);
			btnFav1.setBackground(Color.red);
			btnFav3.setBackground(Color.red);
			btnFav2.setBackground(Color.red);
			btnFav5.setBackground(Color.red);
			btnFav4.setBackground(Color.red);
			btnFav7.setBackground(Color.red);
			btnFav8.setBackground(Color.red);
			btnFav6.setBackground(Color.red);
			btnFav10.setBackground(Color.red);
			btnFav11.setBackground(Color.red);
			btnFav9.setBackground(Color.red);
    }

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
		miRadio.cambiarEstacion(true);
		lblEstacion.setText(Double.toString(miRadio.getEstacion()));
		btnFav12.setBackground(Color.red);
			btnFav1.setBackground(Color.red);
			btnFav3.setBackground(Color.red);
			btnFav2.setBackground(Color.red);
			btnFav5.setBackground(Color.red);
			btnFav4.setBackground(Color.red);
			btnFav7.setBackground(Color.red);
			btnFav8.setBackground(Color.red);
			btnFav6.setBackground(Color.red);
			btnFav10.setBackground(Color.red);
			btnFav11.setBackground(Color.red);
			btnFav9.setBackground(Color.red);
    }

    private void btnFav1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
		if(miRadio.getEstacionesFav()[1]==null){
			miRadio.guardarEstacion(miRadio.getEstacion(),1);
		}
		btnFav1.setBackground(Color.green);
			btnFav2.setBackground(Color.red);
			btnFav3.setBackground(Color.red);
			btnFav4.setBackground(Color.red);
			btnFav5.setBackground(Color.red);
			btnFav6.setBackground(Color.red);
			btnFav7.setBackground(Color.red);
			btnFav8.setBackground(Color.red);
			btnFav9.setBackground(Color.red);
			btnFav10.setBackground(Color.red);
			btnFav11.setBackground(Color.red);
			btnFav12.setBackground(Color.red);
		lblEstacion.setText(miRadio.getEstacionesFav()[1]);
        // TODO add your handling code here:
    }
	private void btnFav2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
		if(miRadio.getEstacionesFav()[2]==null){
			miRadio.guardarEstacion(miRadio.getEstacion(),2);
		}
			btnFav2.setBackground(Color.green);
			btnFav1.setBackground(Color.red);
			btnFav3.setBackground(Color.red);
			btnFav4.setBackground(Color.red);
			btnFav5.setBackground(Color.red);
			btnFav6.setBackground(Color.red);
			btnFav7.setBackground(Color.red);
			btnFav8.setBackground(Color.red);
			btnFav9.setBackground(Color.red);
			btnFav10.setBackground(Color.red);
			btnFav11.setBackground(Color.red);
			btnFav12.setBackground(Color.red);
		lblEstacion.setText(miRadio.getEstacionesFav()[2]);
        // TODO add your handling code here:
    }

    private void btnFav3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
		if(miRadio.getEstacionesFav()[3]==null){
			miRadio.guardarEstacion(miRadio.getEstacion(),3);
		}
			btnFav3.setBackground(Color.green);
			btnFav2.setBackground(Color.red);
			btnFav1.setBackground(Color.red);
			btnFav4.setBackground(Color.red);
			btnFav5.setBackground(Color.red);
			btnFav6.setBackground(Color.red);
			btnFav7.setBackground(Color.red);
			btnFav8.setBackground(Color.red);
			btnFav9.setBackground(Color.red);
			btnFav10.setBackground(Color.red);
			btnFav11.setBackground(Color.red);
			btnFav12.setBackground(Color.red);
		lblEstacion.setText(miRadio.getEstacionesFav()[3]);
    }

    private void btnFav4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
		if(miRadio.getEstacionesFav()[4]==null){
			miRadio.guardarEstacion(miRadio.getEstacion(),4);
		}
			btnFav4.setBackground(Color.green);
			btnFav1.setBackground(Color.red);
			btnFav3.setBackground(Color.red);
			btnFav2.setBackground(Color.red);
			btnFav5.setBackground(Color.red);
			btnFav6.setBackground(Color.red);
			btnFav7.setBackground(Color.red);
			btnFav8.setBackground(Color.red);
			btnFav9.setBackground(Color.red);
			btnFav10.setBackground(Color.red);
			btnFav11.setBackground(Color.red);
			btnFav12.setBackground(Color.red);
		lblEstacion.setText(miRadio.getEstacionesFav()[4]);
    }

    private void btnFav5ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
		if(miRadio.getEstacionesFav()[5]==null){
			miRadio.guardarEstacion(miRadio.getEstacion(),5);
		}
			btnFav5.setBackground(Color.green);
			btnFav1.setBackground(Color.red);
			btnFav3.setBackground(Color.red);
			btnFav2.setBackground(Color.red);
			btnFav4.setBackground(Color.red);
			btnFav6.setBackground(Color.red);
			btnFav7.setBackground(Color.red);
			btnFav8.setBackground(Color.red);
			btnFav9.setBackground(Color.red);
			btnFav10.setBackground(Color.red);
			btnFav11.setBackground(Color.red);
			btnFav12.setBackground(Color.red);
		lblEstacion.setText(miRadio.getEstacionesFav()[5]);
    }

    private void btnFav6ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
		if(miRadio.getEstacionesFav()[6]==null){
			miRadio.guardarEstacion(miRadio.getEstacion(),6);
		}
			btnFav6.setBackground(Color.green);
			btnFav1.setBackground(Color.red);
			btnFav3.setBackground(Color.red);
			btnFav2.setBackground(Color.red);
			btnFav5.setBackground(Color.red);
			btnFav4.setBackground(Color.red);
			btnFav7.setBackground(Color.red);
			btnFav8.setBackground(Color.red);
			btnFav9.setBackground(Color.red);
			btnFav10.setBackground(Color.red);
			btnFav11.setBackground(Color.red);
			btnFav12.setBackground(Color.red);
		lblEstacion.setText(miRadio.getEstacionesFav()[6]);
    }

    private void btnFav7ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
		if(miRadio.getEstacionesFav()[7]==null){
			miRadio.guardarEstacion(miRadio.getEstacion(),7);
		}
			btnFav7.setBackground(Color.green);
			btnFav1.setBackground(Color.red);
			btnFav3.setBackground(Color.red);
			btnFav2.setBackground(Color.red);
			btnFav5.setBackground(Color.red);
			btnFav4.setBackground(Color.red);
			btnFav6.setBackground(Color.red);
			btnFav8.setBackground(Color.red);
			btnFav9.setBackground(Color.red);
			btnFav10.setBackground(Color.red);
			btnFav11.setBackground(Color.red);
			btnFav12.setBackground(Color.red);
		lblEstacion.setText(miRadio.getEstacionesFav()[7]);
    }

    private void btnFav8ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
		if(miRadio.getEstacionesFav()[8]==null){
			miRadio.guardarEstacion(miRadio.getEstacion(),8);
		}
			btnFav8.setBackground(Color.green);
			btnFav1.setBackground(Color.red);
			btnFav3.setBackground(Color.red);
			btnFav2.setBackground(Color.red);
			btnFav5.setBackground(Color.red);
			btnFav4.setBackground(Color.red);
			btnFav7.setBackground(Color.red);
			btnFav6.setBackground(Color.red);
			btnFav9.setBackground(Color.red);
			btnFav10.setBackground(Color.red);
			btnFav11.setBackground(Color.red);
			btnFav12.setBackground(Color.red);
		lblEstacion.setText(miRadio.getEstacionesFav()[8]);
    }

    private void btnFav9ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
		if(miRadio.getEstacionesFav()[9]==null){
			miRadio.guardarEstacion(miRadio.getEstacion(),9);
		}
			btnFav9.setBackground(Color.green);
			btnFav1.setBackground(Color.red);
			btnFav3.setBackground(Color.red);
			btnFav2.setBackground(Color.red);
			btnFav5.setBackground(Color.red);
			btnFav4.setBackground(Color.red);
			btnFav7.setBackground(Color.red);
			btnFav8.setBackground(Color.red);
			btnFav6.setBackground(Color.red);
			btnFav10.setBackground(Color.red);
			btnFav11.setBackground(Color.red);
			btnFav12.setBackground(Color.red);
		lblEstacion.setText(miRadio.getEstacionesFav()[9]);
    }

    private void btnFav10ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
		if(miRadio.getEstacionesFav()[10]==null){
			miRadio.guardarEstacion(miRadio.getEstacion(),10);
		}
			btnFav10.setBackground(Color.green);
			btnFav1.setBackground(Color.red);
			btnFav3.setBackground(Color.red);
			btnFav2.setBackground(Color.red);
			btnFav5.setBackground(Color.red);
			btnFav4.setBackground(Color.red);
			btnFav7.setBackground(Color.red);
			btnFav8.setBackground(Color.red);
			btnFav6.setBackground(Color.red);
			btnFav9.setBackground(Color.red);
			btnFav11.setBackground(Color.red);
			btnFav12.setBackground(Color.red);
		lblEstacion.setText(miRadio.getEstacionesFav()[10]);
    }

    private void btnFav11ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
		if(miRadio.getEstacionesFav()[11]==null){
			miRadio.guardarEstacion(miRadio.getEstacion(),11);
		}
			btnFav11.setBackground(Color.green);
			btnFav1.setBackground(Color.red);
			btnFav3.setBackground(Color.red);
			btnFav2.setBackground(Color.red);
			btnFav5.setBackground(Color.red);
			btnFav4.setBackground(Color.red);
			btnFav7.setBackground(Color.red);
			btnFav8.setBackground(Color.red);
			btnFav6.setBackground(Color.red);
			btnFav10.setBackground(Color.red);
			btnFav9.setBackground(Color.red);
			btnFav12.setBackground(Color.red);
		lblEstacion.setText(miRadio.getEstacionesFav()[11]);
    }

    private void btnFav12ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
		if(miRadio.getEstacionesFav()[12]==null){
			miRadio.guardarEstacion(miRadio.getEstacion(),12);
		}
			btnFav12.setBackground(Color.green);
			btnFav1.setBackground(Color.red);
			btnFav3.setBackground(Color.red);
			btnFav2.setBackground(Color.red);
			btnFav5.setBackground(Color.red);
			btnFav4.setBackground(Color.red);
			btnFav7.setBackground(Color.red);
			btnFav8.setBackground(Color.red);
			btnFav6.setBackground(Color.red);
			btnFav10.setBackground(Color.red);
			btnFav11.setBackground(Color.red);
			btnFav9.setBackground(Color.red);
		lblEstacion.setText(miRadio.getEstacionesFav()[12]);
    }

    private void btnEstadoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
		miRadio.encendidoApagado();
		if(miRadio.getEstado()==true){
			btnFav1.setEnabled(true);
			btnFav2.setEnabled(true);
			btnFav3.setEnabled(true);
			btnFav4.setEnabled(true);
			btnFav5.setEnabled(true);
			btnFav6.setEnabled(true);
			btnFav7.setEnabled(true);
			btnFav8.setEnabled(true);
			btnFav9.setEnabled(true);
			btnFav10.setEnabled(true);
			btnFav11.setEnabled(true);
			btnFav12.setEnabled(true);
			btnAnterior.setEnabled(true);
			btnSiguiente.setEnabled(true);
			btnFrecuencia.setEnabled(true);
			btnEstado.setBackground(Color.green);
		}
		else{
			btnFav1.setEnabled(false);
			btnFav2.setEnabled(false);
			btnFav3.setEnabled(false);
			btnFav4.setEnabled(false);
			btnFav5.setEnabled(false);
			btnFav6.setEnabled(false);
			btnFav7.setEnabled(false);
			btnFav8.setEnabled(false);
			btnFav9.setEnabled(false);
			btnFav10.setEnabled(false);
			btnFav11.setEnabled(false);
			btnFav12.setEnabled(false);
			btnAnterior.setEnabled(false);
			btnSiguiente.setEnabled(false);
			btnFrecuencia.setEnabled(false);
			btnEstado.setBackground(Color.red);
		}
    }

    private void btnFrecuenciaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
		miRadio.cambiarFrecuencia();
		if(miRadio.getAmFm()==true){
			btnFrecuencia.setBackground(Color.yellow);
			btnFrecuencia.setText("AM");
		}
		else{
			btnFrecuencia.setBackground(Color.cyan);
			btnFrecuencia.setText("FM");
		}
    }


    // Variables declaration - do not modify
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnFav8;
    private javax.swing.JButton btnFav9;
    private javax.swing.JButton btnFav10;
    private javax.swing.JButton btnFav11;
    private javax.swing.JButton btnFav12;
    private javax.swing.JButton btnFrecuencia;
    private javax.swing.JButton btnEstado;
    private javax.swing.JButton btnFav1;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnFav2;
    private javax.swing.JButton btnFav3;
    private javax.swing.JButton btnFav4;
    private javax.swing.JButton btnFav5;
    private javax.swing.JButton btnFav6;
    private javax.swing.JButton btnFav7;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblEstacion;
    // End of variables declaration

}
